# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repositories:
# https://github.com/docker/awesome-compose
services:
  app:
    container_name: app
    build:
      context: .
      target: base
    command: bun run dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_SUPABASE_URL: "http://localhost:54321"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
      NEXT_PUBLIC_SENTRY_DSN: "https://62f2197e091c8ff85da928993556e963@o4506681532350464.ingest.sentry.io/4506681534775296"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
  test:
    container_name: test
    build:
      context: .
      target: test
    command: bun run dev:coverage
    environment:
      NODE_ENV: test
      NEXT_PUBLIC_SUPABASE_URL: "postgres://postgres.oyvjtsuxxxulqctgwzbq:GiftPol2023!@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dmp0c3V4eHh1bHFjdGd3emJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ2MjUzNzIsImV4cCI6MjAzMDIwMTM3Mn0.feOkqflx4figeGzwKrIwFkkbOSbrODoiuJsIpXbzcIw"
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    restart: always

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
