name: Main
on:
  push:

env:
  SLACK_USERNAME: GithubActionBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Bun.sh
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: setup DB
      run: docker-compose up -d db-test

    - name: setup drizzle
      run: bun db:generate:test

    - name: Run unit test
      run: bun run test

    - name: Setup playwright
      run: bun playwright install --with-deps

    - name: Run Playwright tests
      run: bun e2e:ci

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Notify deployment
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: ${{ job.status }}
        fields: all
      env:
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTO_MERGE_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
