name: Main
on:
  push:

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set .node-version
      run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: yarn install --frozen-lockfile

    - name: Install dependencies
      run: yarn

    - name: Run jest
      run: yarn test

    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./yarn.lock').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - run: yarn playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - run: yarn playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - name: Run application server
      run: yarn dev &

    - name: Run Playwright tests
      run: yarn e2e

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Slack Notification on Success
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: Deploy Success
        SLACK_COLOR: good

    - name: Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: Deploy Failure
        SLACK_COLOR: danger